#!/bin/bash

set -e

# This script is for deploying given lambda to personal account.

if [ $# -lt 1 ]; then
    echo "Usage:"
    echo "\tnpm run update -- <handler-file-name>"
    echo "Sample Usage:"
    echo "\tnpm run update -- save-travel-post"
    exit 1
fi

handlerFileName=$1

profile="ly-website"
outFile="dist/index.js"
zipFile="dist/lambda.zip"
lambdaName="$(echo "$handlerFileName" | awk -F"-" '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) substr($i,2)}} 1' OFS="")"
echo "lambda name = $lambdaName"

# Clean up
rm -rf dist
# rm -rf "$zipFile"

# Find file name
filePath=$(find src -name "$handlerFileName.handler.ts")

# Build the handler to index.js
npx esbuild --bundle "$filePath" --outfile="$outFile" --platform=node --sourcemap --external:sharp

# Zip file for uploading to lambda
zip -j "$zipFile" "$outFile" "dist/index.js.map"

# Zipping extra dependencies for CreateThumbnail lambda only
if [ "$lambdaName" == "CreateThumbnail" ]; then
    echo 'Adding node_modules/sharp to the zip'
    cd dist
    mkdir node_modules
    cp -r ../../sharp-only/node_modules/* ./node_modules
    zip -ur "../$zipFile" "node_modules"
    cd -
fi

# Upload the zip to lambda
echo "Uploading the zip file to the lambda"
aws lambda update-function-code \
    --function-name "$lambdaName" \
    --profile=$profile \
    --zip-file "fileb://$zipFile" | cat
