#!/bin/bash

set -e

# This script is for deploying given lambda to personal account.

if [ $# -lt 1 ]; then
    echo "Usage:"
    echo "\tnpm run update -- <handler-file-name>"
    echo "Sample Usage:"
    echo "\tnpm run update -- save-travel-post"
    exit 1
fi

handlerFileName=$1

outFile="dist/index.js"
zipFile="dist/lambda.zip"
lambdaName="$(echo "$handlerFileName" | awk -F"-" '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) substr($i,2)}} 1' OFS="")"
echo "lambda name = $lambdaName"

# Clean up
rm -rf "$zipFile"

# Find file name
filePath=$(find src -name "$handlerFileName.handler.ts")

# Build the handler to index.js
./node_modules/esbuild/bin/esbuild --bundle "$filePath" --outfile="$outFile" --platform=node --sourcemap

# Zip file for uploading to lambda
zip -j "$zipFile" "$outFile" "dist/index.js.map"

# Upload the zip to lambda
aws lambda update-function-code \
    --function-name "$lambdaName" \
    --zip-file "fileb://$zipFile"
